name: Bug Report
description: Report a bug or issue with ZenOS
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!
        
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: What part of ZenOS is affected?
      options:
        - Dashboard (Web UI)
        - ZenRX Miner
        - ISO/Boot
        - Rig Agent
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: input
    id: rig-id
    attributes:
      label: Rig ID (if applicable)
      description: You can find this in the dashboard
      placeholder: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

  - type: dropdown
    id: browser
    attributes:
      label: Browser (for dashboard issues)
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other

  - type: textarea
    id: debug
    attributes:
      label: Debug Output
      description: If Debug Mode is enabled, paste relevant output here
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help
