name: Feature Request
description: Suggest a new feature for ZenOS
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: What part of ZenOS would this affect?
      options:
        - Dashboard (Web UI)
        - ZenRX Miner
        - ISO/Boot
        - Rig Agent
        - New Component
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other solutions you've thought about?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, mockups, or examples
